// Generated by CoffeeScript 1.6.2
$(function() {
  this.model = new dropmodel(this.refs);
  this.view = new dropview(this.refs, this.model);
  $("section.span12").css({
    "background-color": "#FEE"
  });
  $(".row").css("height", "400");
  $("#selectionbox").css({
    "height": "100%"
  });
  $("#main").css({
    "background-color": "#EEE",
    "height": "100%"
  });
  $(".selectlist").css({
    "background-color": "#DDD"
  });
  return $(".method").css({
    "margin": "2%",
    "background-color": "#EEF"
  });
});
