// Generated by CoffeeScript 1.6.2
var dropmodel;

dropmodel = (function() {
  function dropmodel(refs) {
    this.refs = refs;
    this.ondropboxchange_callbacks = [];
    this.onregexpchange_callbacks = [];
  }

  dropmodel.prototype.ondropboxchange = function(callback, context) {
    return this.ondropboxchange_callbacks.push([callback, context]);
  };

  dropmodel.prototype.onregexpchange = function(callback, context) {
    return this.onregexpchange_callbacks.push([callback, context]);
  };

  dropmodel.prototype.extractcontent = function($obj) {
    $obj.trigger("content");
    return $obj.attr("content");
  };

  dropmodel.prototype.updatedropbox = function(event, ui) {
    var callback, context, _i, _len, _ref, _ref1, _results;

    _ref = this.ondropboxchange_callbacks;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], callback = _ref1[0], context = _ref1[1];
      _results.push(callback(ui.draggable.clone(), context));
    }
    return _results;
  };

  dropmodel.prototype.updateregexp = function(verbalexp) {
    var callback, context, regexp, _i, _len, _ref, _ref1, _results;

    regexp = eval("VerEx()" + verbalexp);
    _ref = this.onregexpchange_callbacks;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], callback = _ref1[0], context = _ref1[1];
      _results.push(callback(regexp, context));
    }
    return _results;
  };

  return dropmodel;

})();
