// Generated by CoffeeScript 1.6.2
$(function() {
  var $verexinput;

  $verexinput = $("#verextext");
  $(".draggable").draggable({
    helper: "clone",
    appendTo: "body"
  });
  $("#test").draggable();
  $("section.span12").css({
    "background-color": "#FEE"
  });
  $(".row").css("height", "100");
  $("#sub").css({
    "height": "100%"
  });
  $("#main").css({
    "background-color": "#EEE",
    "height": "100%"
  });
  $(".selectlist").css({
    "background-color": "#DDD"
  });
  $(".method").css({
    "background-color": "#EEF"
  });
  $("*.dropbox").droppable({
    accept: ".draggable",
    over: function(event, ui) {},
    drop: function(event, ui) {
      console.log(ui.draggable);
      $verexinput.val($verexinput.val() + ui.draggable.find("p").text());
      return $(this).append(ui.draggable.clone());
    }
  });
  $verexinput.val("VerEx()");
  $verexinput["eval"] = function() {
    console.log(eval(this.val()));
    return console.log(eval("1+1"));
  };
  return $("#verexeval").click(function() {
    return $verexinput["eval"]();
  });
});
